// Code generated by go-bindata. DO NOT EDIT.
// sources:
// templates/header.md.jinja2 (63B)
// templates/ranks.md.jinja2 (82B)
// templates/stats.md.jinja2 (169B)

package templates

import (
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("read %q: %w", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("read %q: %w", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes  []byte
	info   os.FileInfo
	digest [sha256.Size]byte
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _templatesHeaderMdJinja2 = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x52\x56\xb0\x2a\x4e\xaa\xd4\x4d\xd4\xcd\x4b\x2d\xd7\x4d\xcd\xcd\xcf\xca\xb4\x52\x70\x05\x51\x0a\x41\xa9\x39\xa9\x89\xc5\xa9\x0a\x7e\xf9\x25\xa9\xc5\x0a\xd5\xd5\x0a\xc5\x25\x89\x45\x25\x0a\xb5\xb5\x0a\xba\x20\x5e\x6a\x5e\x8a\x42\x6d\x2d\x20\x00\x00\xff\xff\x76\xc0\xe2\xbb\x3f\x00\x00\x00")

func templatesHeaderMdJinja2Bytes() ([]byte, error) {
	return bindataRead(
		_templatesHeaderMdJinja2,
		"templates/header.md.jinja2",
	)
}

func templatesHeaderMdJinja2() (*asset, error) {
	bytes, err := templatesHeaderMdJinja2Bytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/header.md.jinja2", size: 63, mode: os.FileMode(0644), modTime: time.Unix(1770326844, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x8a, 0x3, 0xf8, 0xfd, 0x98, 0x8d, 0x76, 0x4c, 0xf3, 0xca, 0x62, 0x3, 0x5c, 0x4c, 0xe7, 0xf8, 0x78, 0x69, 0x4d, 0xf7, 0xf0, 0x9c, 0x62, 0x22, 0x67, 0x8c, 0xd, 0xaf, 0xc4, 0xf8, 0xe, 0x69}}
	return a, nil
}

var _templatesRanksMdJinja2 = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x52\x56\xb0\x2a\x4e\xaa\xd4\x4d\xd4\xcd\x4b\x2d\xd7\x4d\xcd\xcd\xcf\xca\xb4\x52\x70\x05\x51\x0a\x41\xa9\x39\xa9\x89\xc5\xa9\x0a\x7e\xf9\x25\xa9\xc5\x5c\x5c\xca\xca\x0a\xc1\x05\x45\x99\x79\x25\x0a\xa1\x05\x39\xf9\x89\x29\xa9\x45\xc5\x5c\x5c\x09\x09\x09\x5c\xd5\xd5\x0a\x45\x89\x79\xd9\xc5\x0a\xb5\xb5\x60\x3e\x20\x00\x00\xff\xff\x48\x36\x99\xf9\x52\x00\x00\x00")

func templatesRanksMdJinja2Bytes() ([]byte, error) {
	return bindataRead(
		_templatesRanksMdJinja2,
		"templates/ranks.md.jinja2",
	)
}

func templatesRanksMdJinja2() (*asset, error) {
	bytes, err := templatesRanksMdJinja2Bytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/ranks.md.jinja2", size: 82, mode: os.FileMode(0644), modTime: time.Unix(1770830550, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xd4, 0x33, 0x6e, 0xb2, 0x89, 0x78, 0xf2, 0x9a, 0x85, 0x26, 0xbf, 0xc8, 0x8a, 0xe1, 0x63, 0xda, 0xe4, 0xfd, 0xff, 0xc0, 0x56, 0xed, 0xe2, 0x9c, 0xe3, 0x24, 0x18, 0x4d, 0xef, 0x76, 0x4c, 0x1b}}
	return a, nil
}

var _templatesStatsMdJinja2 = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xaa\xae\x56\x28\xc9\x2f\x88\x37\x32\x55\xa8\x51\x28\x49\x4c\x2a\xcd\x49\x2c\x49\x55\xa8\xad\xe5\xe2\xb2\xb4\x2c\xc9\x50\x08\x48\x2d\x4a\x4e\xcd\x2b\xc9\xcc\x49\xb5\x52\xa8\xae\x56\x28\x48\x8e\xb7\xb4\x04\xc9\x5a\x1a\x60\x97\x34\x00\x49\x86\xe4\x17\x28\x04\x96\x26\x16\x41\x64\x14\x14\xa0\x92\xe6\xa6\x20\x49\xdf\xcc\x94\x94\x9c\x54\x24\x79\x88\xa4\x29\x58\xa7\x53\x7e\x49\x49\x7e\x2e\x86\xa4\x11\x48\x27\x20\x00\x00\xff\xff\x3a\x4a\xe0\xdd\xa9\x00\x00\x00")

func templatesStatsMdJinja2Bytes() ([]byte, error) {
	return bindataRead(
		_templatesStatsMdJinja2,
		"templates/stats.md.jinja2",
	)
}

func templatesStatsMdJinja2() (*asset, error) {
	bytes, err := templatesStatsMdJinja2Bytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/stats.md.jinja2", size: 169, mode: os.FileMode(0644), modTime: time.Unix(1770326844, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x31, 0x8f, 0x72, 0xe9, 0x73, 0x6e, 0x52, 0x27, 0x91, 0xed, 0x6e, 0x2e, 0x1c, 0xa8, 0x12, 0xb1, 0xd3, 0x38, 0x4a, 0x54, 0x13, 0x7d, 0x83, 0xfe, 0x36, 0x1e, 0xdc, 0x36, 0x17, 0x9c, 0x10, 0x4}}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// AssetString returns the asset contents as a string (instead of a []byte).
func AssetString(name string) (string, error) {
	data, err := Asset(name)
	return string(data), err
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// MustAssetString is like AssetString but panics when Asset would return an
// error. It simplifies safe initialization of global variables.
func MustAssetString(name string) string {
	return string(MustAsset(name))
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetDigest returns the digest of the file with the given name. It returns an
// error if the asset could not be found or the digest could not be loaded.
func AssetDigest(name string) ([sha256.Size]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s can't read by error: %v", name, err)
		}
		return a.digest, nil
	}
	return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s not found", name)
}

// Digests returns a map of all known files and their checksums.
func Digests() (map[string][sha256.Size]byte, error) {
	mp := make(map[string][sha256.Size]byte, len(_bindata))
	for name := range _bindata {
		a, err := _bindata[name]()
		if err != nil {
			return nil, err
		}
		mp[name] = a.digest
	}
	return mp, nil
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"templates/header.md.jinja2": templatesHeaderMdJinja2,
	"templates/ranks.md.jinja2":  templatesRanksMdJinja2,
	"templates/stats.md.jinja2":  templatesStatsMdJinja2,
}

// AssetDebug is true if the assets were built with the debug flag enabled.
const AssetDebug = false

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//
//	data/
//	  foo.txt
//	  img/
//	    a.png
//	    b.png
//
// then AssetDir("data") would return []string{"foo.txt", "img"},
// AssetDir("data/img") would return []string{"a.png", "b.png"},
// AssetDir("foo.txt") and AssetDir("notexist") would return an error, and
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		canonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(canonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"templates": {nil, map[string]*bintree{
		"header.md.jinja2": {templatesHeaderMdJinja2, map[string]*bintree{}},
		"ranks.md.jinja2":  {templatesRanksMdJinja2, map[string]*bintree{}},
		"stats.md.jinja2":  {templatesStatsMdJinja2, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory.
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = os.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	return os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
}

// RestoreAssets restores an asset under the given directory recursively.
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(canonicalName, "/")...)...)
}
