// Code generated by go-bindata. DO NOT EDIT.
// sources:
// templates/doc_index.md.gotmpl (107B)
// templates/doc_page.md.gotmpl (519B)
// templates/header.md.gotmpl (65B)
// templates/ranks.md.gotmpl (147B)

package templates

import (
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("read %q: %w", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("read %q: %w", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes  []byte
	info   os.FileInfo
	digest [sha256.Size]byte
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _templatesDoc_indexMdGotmpl = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xaa\xae\x56\xc9\x2b\x56\xb0\xb2\x55\xd0\xf3\x4b\xcc\x4d\x2d\x2e\x48\x4c\x4e\x55\xd0\xad\xad\xe5\x52\x56\x70\xcd\xcd\xcf\xca\x2c\xe6\xe2\xd2\xd5\xd5\xe5\xe2\xaa\xae\x2e\x4a\xcc\x4b\x4f\x55\xd0\x0b\x48\x4c\x4f\x2d\x06\xab\xd0\x52\x88\xae\xae\x06\xeb\xaa\xad\x8d\xd5\xd0\x4f\xc9\x4f\x2e\xd6\x07\x9b\x56\x5b\xab\x0f\x97\xd0\xcb\x4d\xd1\xe4\xaa\xae\x4e\xcd\x4b\xa9\xad\x05\x04\x00\x00\xff\xff\xd2\x05\x3c\x6a\x6b\x00\x00\x00")

func templatesDoc_indexMdGotmplBytes() ([]byte, error) {
	return bindataRead(
		_templatesDoc_indexMdGotmpl,
		"templates/doc_index.md.gotmpl",
	)
}

func templatesDoc_indexMdGotmpl() (*asset, error) {
	bytes, err := templatesDoc_indexMdGotmplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/doc_index.md.gotmpl", size: 107, mode: os.FileMode(0644), modTime: time.Unix(1771972135, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x8, 0xf0, 0xd4, 0x55, 0x55, 0x1c, 0x6, 0xa7, 0x49, 0x28, 0x8d, 0x72, 0xf6, 0xb4, 0xc3, 0x5d, 0xe9, 0xf8, 0xff, 0x26, 0x4c, 0x59, 0x3b, 0xee, 0xfa, 0x71, 0xf8, 0xb0, 0xb2, 0xd7, 0x45, 0x92}}
	return a, nil
}

var _templatesDoc_pageMdGotmpl = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x8c\x90\x3d\x4e\xc3\x40\x10\x85\xfb\x3d\xc5\xc3\x34\x76\xb1\xa6\x4f\xcb\x8f\x44\x13\xa5\xb7\x52\x2c\x78\x62\x2d\xd8\x6b\xc9\x76\x22\xa4\xd9\xb9\x04\x35\x12\x57\xe4\x08\x68\xbc\x49\x48\x00\x09\x9a\xd5\xec\x9b\x99\xef\x3d\x0d\xb3\x45\x4d\x1b\x1f\x08\x59\x70\x3b\xdf\xb8\xc9\xf7\x21\x83\x88\x61\x86\xdf\x20\x77\xa1\x46\x1e\x08\xe5\x92\x5e\xa6\x95\x6b\x08\x59\x56\x24\x65\x35\xd0\xee\xa0\x14\xb0\x22\xa6\x52\xc9\xf7\xdb\x11\xaa\xaf\x73\xe6\xe3\x90\x48\x81\x88\x4a\x29\x5f\xcd\x03\x53\xa4\x50\x3f\x6a\x47\x9a\x4d\xbf\xd3\xff\x05\xff\x41\x38\x4b\xac\x84\x3f\xfd\x43\x3d\xcf\x9d\x94\x97\xb8\xed\xfa\x27\x3f\x22\x9f\x49\xcc\xe5\x75\xbf\x0d\x53\x5a\x78\x68\xfb\xc7\xe7\xf3\xc3\x95\xba\xa5\x57\xa5\x50\x8b\x18\x6b\xad\x35\x26\x26\x08\x96\xae\x23\x44\xdc\x77\x8a\x8a\x26\x62\x61\x17\xd8\xbf\x86\x79\x70\xa1\x21\x94\x7b\xc3\x14\x58\x43\xba\x8e\x44\x10\x71\x51\x1d\x7f\xeb\xfc\x8a\xb9\xbc\xf1\x83\x88\x16\x77\xbe\xa5\x30\x37\xd2\x1d\x4e\xcc\x7f\x4f\xa9\x19\xd3\xd0\xc7\xfb\xeb\x9b\xf9\x0c\x00\x00\xff\xff\x43\x8a\x30\x6f\x07\x02\x00\x00")

func templatesDoc_pageMdGotmplBytes() ([]byte, error) {
	return bindataRead(
		_templatesDoc_pageMdGotmpl,
		"templates/doc_page.md.gotmpl",
	)
}

func templatesDoc_pageMdGotmpl() (*asset, error) {
	bytes, err := templatesDoc_pageMdGotmplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/doc_page.md.gotmpl", size: 519, mode: os.FileMode(0644), modTime: time.Unix(1771972135, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xb, 0x5f, 0x0, 0x97, 0x4f, 0xfb, 0x22, 0xce, 0xa, 0x7, 0xfd, 0x18, 0x7c, 0xd1, 0xac, 0xc6, 0xf0, 0xf4, 0x5f, 0xad, 0xaa, 0xee, 0xa9, 0x1b, 0x13, 0x3f, 0x4f, 0xda, 0xa0, 0xdc, 0x53, 0xb4}}
	return a, nil
}

var _templatesHeaderMdGotmpl = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x52\x56\xb0\x2a\x4e\xaa\xd4\x4d\xd4\xcd\x4b\x2d\xd7\x4d\xcd\xcd\xcf\xca\xb4\x52\x70\x05\x51\x0a\x41\xa9\x39\xa9\x89\xc5\xa9\x0a\x7e\xf9\x25\xa9\xc5\x0a\xd5\xd5\x0a\x7a\xc5\x25\x89\x45\x25\x0a\xb5\xb5\x0a\xba\x60\x6e\x6a\x5e\x8a\x42\x6d\x2d\x20\x00\x00\xff\xff\x88\xdc\x37\xc0\x41\x00\x00\x00")

func templatesHeaderMdGotmplBytes() ([]byte, error) {
	return bindataRead(
		_templatesHeaderMdGotmpl,
		"templates/header.md.gotmpl",
	)
}

func templatesHeaderMdGotmpl() (*asset, error) {
	bytes, err := templatesHeaderMdGotmplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/header.md.gotmpl", size: 65, mode: os.FileMode(0644), modTime: time.Unix(1771972135, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xa0, 0x78, 0x45, 0x13, 0x18, 0xd2, 0xa3, 0x59, 0x57, 0xfc, 0xff, 0xd0, 0x6a, 0xb4, 0x60, 0xcc, 0xb5, 0x53, 0xdf, 0x3c, 0x29, 0x34, 0x6d, 0xd2, 0xc8, 0xc6, 0x42, 0x76, 0x95, 0x56, 0x7b, 0xe9}}
	return a, nil
}

var _templatesRanksMdGotmpl = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x2c\x8d\xc1\xca\xc2\x30\x10\x84\xef\xfb\x14\x03\xfd\x4f\x3f\x24\x0f\x10\xf0\xe8\x49\xf0\x50\xf0\x01\x56\xb2\x94\x68\xdd\x94\x44\xd0\xb2\xec\xbb\x4b\xab\xa7\x99\x39\xcc\xf7\x99\xfd\x35\xd6\x7b\x47\x3a\x20\x8e\x7b\x0b\xee\x34\x20\xf5\xeb\x1a\x38\xa8\xbc\x82\x3c\xea\xad\x24\x1c\xb7\xc0\x28\xb3\x70\x17\x9c\xeb\x53\x3a\xd1\x30\xe0\xb2\xcc\x95\xb3\xb4\x4e\x64\xd6\x58\x27\x41\x3c\xc9\xfa\x05\xfd\xc3\x0c\x11\xee\x66\x0b\xe7\x5c\x74\x42\xdc\x46\xd1\x2c\x6f\xfc\xdc\xd1\x9d\xcc\x44\xf3\x7e\xf9\x04\x00\x00\xff\xff\x81\xff\x93\x19\x93\x00\x00\x00")

func templatesRanksMdGotmplBytes() ([]byte, error) {
	return bindataRead(
		_templatesRanksMdGotmpl,
		"templates/ranks.md.gotmpl",
	)
}

func templatesRanksMdGotmpl() (*asset, error) {
	bytes, err := templatesRanksMdGotmplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/ranks.md.gotmpl", size: 147, mode: os.FileMode(0644), modTime: time.Unix(1771972135, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x9b, 0xc9, 0x2e, 0xf1, 0x63, 0x87, 0xb2, 0xd1, 0xaa, 0x4c, 0xfc, 0xc4, 0x85, 0x2f, 0xe2, 0xce, 0x90, 0xb8, 0x1e, 0x64, 0x38, 0x4f, 0x25, 0xfc, 0xd1, 0xe3, 0x83, 0x6d, 0xa, 0x92, 0x28, 0xcd}}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// AssetString returns the asset contents as a string (instead of a []byte).
func AssetString(name string) (string, error) {
	data, err := Asset(name)
	return string(data), err
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// MustAssetString is like AssetString but panics when Asset would return an
// error. It simplifies safe initialization of global variables.
func MustAssetString(name string) string {
	return string(MustAsset(name))
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetDigest returns the digest of the file with the given name. It returns an
// error if the asset could not be found or the digest could not be loaded.
func AssetDigest(name string) ([sha256.Size]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s can't read by error: %v", name, err)
		}
		return a.digest, nil
	}
	return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s not found", name)
}

// Digests returns a map of all known files and their checksums.
func Digests() (map[string][sha256.Size]byte, error) {
	mp := make(map[string][sha256.Size]byte, len(_bindata))
	for name := range _bindata {
		a, err := _bindata[name]()
		if err != nil {
			return nil, err
		}
		mp[name] = a.digest
	}
	return mp, nil
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"templates/doc_index.md.gotmpl": templatesDoc_indexMdGotmpl,
	"templates/doc_page.md.gotmpl":  templatesDoc_pageMdGotmpl,
	"templates/header.md.gotmpl":    templatesHeaderMdGotmpl,
	"templates/ranks.md.gotmpl":     templatesRanksMdGotmpl,
}

// AssetDebug is true if the assets were built with the debug flag enabled.
const AssetDebug = false

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//
//	data/
//	  foo.txt
//	  img/
//	    a.png
//	    b.png
//
// then AssetDir("data") would return []string{"foo.txt", "img"},
// AssetDir("data/img") would return []string{"a.png", "b.png"},
// AssetDir("foo.txt") and AssetDir("notexist") would return an error, and
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		canonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(canonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"templates": {nil, map[string]*bintree{
		"doc_index.md.gotmpl": {templatesDoc_indexMdGotmpl, map[string]*bintree{}},
		"doc_page.md.gotmpl":  {templatesDoc_pageMdGotmpl, map[string]*bintree{}},
		"header.md.gotmpl":    {templatesHeaderMdGotmpl, map[string]*bintree{}},
		"ranks.md.gotmpl":     {templatesRanksMdGotmpl, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory.
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = os.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	return os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
}

// RestoreAssets restores an asset under the given directory recursively.
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(canonicalName, "/")...)...)
}
