// Code generated by go-bindata. DO NOT EDIT.
// sources:
// templates/doc_index.md.gotmpl (107B)
// templates/doc_page.md.gotmpl (508B)
// templates/header.md.gotmpl (65B)
// templates/header.md.jinja2 (63B)
// templates/ranks.md.gotmpl (76B)
// templates/ranks.md.jinja2 (75B)
// templates/stats.md.jinja2 (169B)

package templates

import (
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("read %q: %w", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("read %q: %w", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes  []byte
	info   os.FileInfo
	digest [sha256.Size]byte
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _templatesDoc_indexMdGotmpl = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xaa\xae\x56\xc9\x2b\x56\xb0\xb2\x55\xd0\xf3\x4b\xcc\x4d\x2d\x2e\x48\x4c\x4e\x55\xd0\xad\xad\xe5\x52\x56\x70\xcd\xcd\xcf\xca\x2c\xe6\xe2\xd2\xd5\xd5\xe5\xe2\xaa\xae\x2e\x4a\xcc\x4b\x4f\x55\xd0\x0b\x48\x4c\x4f\x2d\x06\xab\xd0\x52\x88\xae\xae\x06\xeb\xaa\xad\x8d\xd5\xd0\x4f\xc9\x4f\x2e\xd6\x07\x9b\x56\x5b\xab\x0f\x97\xd0\xcb\x4d\xd1\xe4\xaa\xae\x4e\xcd\x4b\xa9\xad\x05\x04\x00\x00\xff\xff\xd2\x05\x3c\x6a\x6b\x00\x00\x00")

func templatesDoc_indexMdGotmplBytes() ([]byte, error) {
	return bindataRead(
		_templatesDoc_indexMdGotmpl,
		"templates/doc_index.md.gotmpl",
	)
}

func templatesDoc_indexMdGotmpl() (*asset, error) {
	bytes, err := templatesDoc_indexMdGotmplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/doc_index.md.gotmpl", size: 107, mode: os.FileMode(0644), modTime: time.Unix(1771458132, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x8, 0xf0, 0xd4, 0x55, 0x55, 0x1c, 0x6, 0xa7, 0x49, 0x28, 0x8d, 0x72, 0xf6, 0xb4, 0xc3, 0x5d, 0xe9, 0xf8, 0xff, 0x26, 0x4c, 0x59, 0x3b, 0xee, 0xfa, 0x71, 0xf8, 0xb0, 0xb2, 0xd7, 0x45, 0x92}}
	return a, nil
}

var _templatesDoc_pageMdGotmpl = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x8c\x90\x31\x4e\xc3\x40\x10\x45\xfb\x3d\xc5\xc7\x34\x76\xb1\x3e\x40\x5a\xa0\xa0\x89\xdc\x5b\x14\x4b\x3c\x31\x0b\xf1\xae\x14\x3b\x11\xd2\xec\x5c\x82\x1a\x89\x2b\x72\x04\x34\x76\x1c\x12\x40\x22\x8d\xe5\xfd\xfb\xe7\xfd\xbf\xc3\x6c\xd1\xd0\xda\x07\x42\x16\xdc\xde\xb7\x6e\xf0\x31\x64\x10\x31\xcc\xf0\x6b\xe4\x2e\x34\xc8\x03\xa1\x5c\xd2\xeb\x50\xb9\x96\x90\x65\xc5\xa4\x54\x5b\xda\xcf\x4a\x01\x2b\x62\x6a\x95\x7c\xdc\xf5\x50\xfd\x21\x67\x3e\x9a\x44\x0a\x24\xd4\x4a\xf9\xbe\x9c\x99\x22\x85\xe6\xd1\xa6\xa7\x31\xf4\x27\xfd\x22\xf8\x2f\xc2\x59\x63\x25\xfc\x9b\x1f\x9a\xd1\x77\xf2\x7b\x8d\xbb\x2e\x3e\xfb\x1e\xf9\x48\x62\x2e\x6f\xe2\x2e\x0c\xd3\xc0\xe3\x26\xae\x5e\xce\x17\x57\xea\x94\x6e\x95\x42\x23\x62\xac\xb5\xd6\x98\x34\x41\xb0\x74\x1d\x21\xe1\xbe\x53\x54\x32\x09\x0b\xbb\xc0\xe1\x6b\x98\xb7\x2e\xb4\x84\xf2\x10\x38\x15\xd6\x92\xae\x23\x11\x24\x5c\xd5\xc7\xd3\xd8\xfe\x36\xae\x2a\x37\x3c\xcd\x8f\x3f\x49\xfc\xbb\x9a\x16\x9b\x4c\x9f\x1f\x6f\xef\xe6\x2b\x00\x00\xff\xff\x8c\xd1\x76\x63\xfc\x01\x00\x00")

func templatesDoc_pageMdGotmplBytes() ([]byte, error) {
	return bindataRead(
		_templatesDoc_pageMdGotmpl,
		"templates/doc_page.md.gotmpl",
	)
}

func templatesDoc_pageMdGotmpl() (*asset, error) {
	bytes, err := templatesDoc_pageMdGotmplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/doc_page.md.gotmpl", size: 508, mode: os.FileMode(0644), modTime: time.Unix(1771346263, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x94, 0x61, 0x9, 0xe4, 0xe0, 0xdd, 0xdb, 0x9e, 0x51, 0x6e, 0xf5, 0x0, 0xbf, 0x5e, 0xe6, 0x28, 0xed, 0xec, 0xf1, 0xdc, 0x8f, 0x73, 0x77, 0x7, 0x3b, 0xf6, 0x19, 0x34, 0xfc, 0x50, 0x15, 0x2d}}
	return a, nil
}

var _templatesHeaderMdGotmpl = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x52\x56\xb0\x2a\x4e\xaa\xd4\x4d\xd4\xcd\x4b\x2d\xd7\x4d\xcd\xcd\xcf\xca\xb4\x52\x70\x05\x51\x0a\x41\xa9\x39\xa9\x89\xc5\xa9\x0a\x7e\xf9\x25\xa9\xc5\x0a\xd5\xd5\x0a\x7a\xc1\x25\x89\x45\x25\x0a\xb5\xb5\x0a\xba\x60\xae\x6b\x5e\x8a\x42\x6d\x2d\x20\x00\x00\xff\xff\x66\xfc\x53\x50\x41\x00\x00\x00")

func templatesHeaderMdGotmplBytes() ([]byte, error) {
	return bindataRead(
		_templatesHeaderMdGotmpl,
		"templates/header.md.gotmpl",
	)
}

func templatesHeaderMdGotmpl() (*asset, error) {
	bytes, err := templatesHeaderMdGotmplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/header.md.gotmpl", size: 65, mode: os.FileMode(0644), modTime: time.Unix(1771459070, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x3d, 0x16, 0x9d, 0xc2, 0x4e, 0xfd, 0xe3, 0xb9, 0x5d, 0x9c, 0x78, 0x23, 0x99, 0xd7, 0xb3, 0x23, 0x71, 0xb, 0x98, 0xff, 0x69, 0x99, 0xda, 0xcb, 0x74, 0x1c, 0x12, 0x1a, 0x9d, 0x12, 0xe0, 0xe6}}
	return a, nil
}

var _templatesHeaderMdJinja2 = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x52\x56\xb0\x2a\x4e\xaa\xd4\x4d\xd4\xcd\x4b\x2d\xd7\x4d\xcd\xcd\xcf\xca\xb4\x52\x70\x05\x51\x0a\x41\xa9\x39\xa9\x89\xc5\xa9\x0a\x7e\xf9\x25\xa9\xc5\x0a\xd5\xd5\x0a\xc5\x25\x89\x45\x25\x0a\xb5\xb5\x0a\xba\x20\x5e\x6a\x5e\x8a\x42\x6d\x2d\x20\x00\x00\xff\xff\x76\xc0\xe2\xbb\x3f\x00\x00\x00")

func templatesHeaderMdJinja2Bytes() ([]byte, error) {
	return bindataRead(
		_templatesHeaderMdJinja2,
		"templates/header.md.jinja2",
	)
}

func templatesHeaderMdJinja2() (*asset, error) {
	bytes, err := templatesHeaderMdJinja2Bytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/header.md.jinja2", size: 63, mode: os.FileMode(0644), modTime: time.Unix(1770326844, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x8a, 0x3, 0xf8, 0xfd, 0x98, 0x8d, 0x76, 0x4c, 0xf3, 0xca, 0x62, 0x3, 0x5c, 0x4c, 0xe7, 0xf8, 0x78, 0x69, 0x4d, 0xf7, 0xf0, 0x9c, 0x62, 0x22, 0x67, 0x8c, 0xd, 0xaf, 0xc4, 0xf8, 0xe, 0x69}}
	return a, nil
}

var _templatesRanksMdGotmpl = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x52\x56\xb0\x2a\x4e\xaa\xd4\x4d\xd4\xcd\x4b\x2d\xd7\x4d\xcd\xcd\xcf\xca\xb4\x52\x70\x05\x51\x0a\x41\xa9\x39\xa9\x89\xc5\xa9\x0a\x7e\xf9\x25\xa9\xc5\x5c\x5c\xca\xca\x0a\xa1\x05\x39\xf9\x89\x29\xa9\x45\xc5\x5c\x5c\x09\x09\x09\x5c\xd5\xd5\x0a\x7a\x41\x89\x79\xd9\xc5\x0a\xb5\xb5\x60\x01\x40\x00\x00\x00\xff\xff\x91\xeb\xb5\x0d\x4c\x00\x00\x00")

func templatesRanksMdGotmplBytes() ([]byte, error) {
	return bindataRead(
		_templatesRanksMdGotmpl,
		"templates/ranks.md.gotmpl",
	)
}

func templatesRanksMdGotmpl() (*asset, error) {
	bytes, err := templatesRanksMdGotmplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/ranks.md.gotmpl", size: 76, mode: os.FileMode(0644), modTime: time.Unix(1771459090, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xce, 0x85, 0x59, 0x60, 0x3a, 0x51, 0x17, 0x84, 0x73, 0x60, 0xc0, 0x17, 0x4b, 0xca, 0x15, 0x9c, 0xee, 0xbd, 0x77, 0x95, 0x57, 0x6a, 0x26, 0xdf, 0xea, 0x93, 0x6d, 0x3e, 0xee, 0xe1, 0xba, 0x76}}
	return a, nil
}

var _templatesRanksMdJinja2 = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x52\x56\xb0\x2a\x4e\xaa\xd4\x4d\xd4\xcd\x4b\x2d\xd7\x4d\xcd\xcd\xcf\xca\xb4\x52\x70\x05\x51\x0a\x41\xa9\x39\xa9\x89\xc5\xa9\x0a\x7e\xf9\x25\xa9\xc5\x5c\x5c\xca\xca\x0a\xa1\x05\x39\xf9\x89\x29\xa9\x45\xc5\x5c\x5c\x09\x09\x09\x5c\xd5\xd5\x0a\x45\x89\x79\xd9\xc5\x0a\xb5\xb5\x60\x3e\x20\x00\x00\xff\xff\x9f\xb5\x00\x6e\x4b\x00\x00\x00")

func templatesRanksMdJinja2Bytes() ([]byte, error) {
	return bindataRead(
		_templatesRanksMdJinja2,
		"templates/ranks.md.jinja2",
	)
}

func templatesRanksMdJinja2() (*asset, error) {
	bytes, err := templatesRanksMdJinja2Bytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/ranks.md.jinja2", size: 75, mode: os.FileMode(0644), modTime: time.Unix(1770834862, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x65, 0xb6, 0x3, 0xfa, 0xb6, 0x65, 0x6e, 0x1d, 0xa2, 0x17, 0xef, 0xc0, 0x40, 0x91, 0xb, 0xc2, 0xfd, 0xfb, 0x8c, 0x51, 0x32, 0xd5, 0x8, 0x2d, 0x75, 0xf1, 0x8b, 0x85, 0xde, 0x13, 0xbf, 0xf1}}
	return a, nil
}

var _templatesStatsMdJinja2 = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xaa\xae\x56\x28\xc9\x2f\x88\x37\x32\x55\xa8\x51\x28\x49\x4c\x2a\xcd\x49\x2c\x49\x55\xa8\xad\xe5\xe2\xb2\xb4\x2c\xc9\x50\x08\x48\x2d\x4a\x4e\xcd\x2b\xc9\xcc\x49\xb5\x52\xa8\xae\x56\x28\x48\x8e\xb7\xb4\x04\xc9\x5a\x1a\x60\x97\x34\x00\x49\x86\xe4\x17\x28\x04\x96\x26\x16\x41\x64\x14\x14\xa0\x92\xe6\xa6\x20\x49\xdf\xcc\x94\x94\x9c\x54\x24\x79\x88\xa4\x29\x58\xa7\x53\x7e\x49\x49\x7e\x2e\x86\xa4\x11\x48\x27\x20\x00\x00\xff\xff\x3a\x4a\xe0\xdd\xa9\x00\x00\x00")

func templatesStatsMdJinja2Bytes() ([]byte, error) {
	return bindataRead(
		_templatesStatsMdJinja2,
		"templates/stats.md.jinja2",
	)
}

func templatesStatsMdJinja2() (*asset, error) {
	bytes, err := templatesStatsMdJinja2Bytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/stats.md.jinja2", size: 169, mode: os.FileMode(0644), modTime: time.Unix(1770326844, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x31, 0x8f, 0x72, 0xe9, 0x73, 0x6e, 0x52, 0x27, 0x91, 0xed, 0x6e, 0x2e, 0x1c, 0xa8, 0x12, 0xb1, 0xd3, 0x38, 0x4a, 0x54, 0x13, 0x7d, 0x83, 0xfe, 0x36, 0x1e, 0xdc, 0x36, 0x17, 0x9c, 0x10, 0x4}}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// AssetString returns the asset contents as a string (instead of a []byte).
func AssetString(name string) (string, error) {
	data, err := Asset(name)
	return string(data), err
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// MustAssetString is like AssetString but panics when Asset would return an
// error. It simplifies safe initialization of global variables.
func MustAssetString(name string) string {
	return string(MustAsset(name))
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetDigest returns the digest of the file with the given name. It returns an
// error if the asset could not be found or the digest could not be loaded.
func AssetDigest(name string) ([sha256.Size]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s can't read by error: %v", name, err)
		}
		return a.digest, nil
	}
	return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s not found", name)
}

// Digests returns a map of all known files and their checksums.
func Digests() (map[string][sha256.Size]byte, error) {
	mp := make(map[string][sha256.Size]byte, len(_bindata))
	for name := range _bindata {
		a, err := _bindata[name]()
		if err != nil {
			return nil, err
		}
		mp[name] = a.digest
	}
	return mp, nil
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"templates/doc_index.md.gotmpl": templatesDoc_indexMdGotmpl,
	"templates/doc_page.md.gotmpl":  templatesDoc_pageMdGotmpl,
	"templates/header.md.gotmpl":    templatesHeaderMdGotmpl,
	"templates/header.md.jinja2":    templatesHeaderMdJinja2,
	"templates/ranks.md.gotmpl":     templatesRanksMdGotmpl,
	"templates/ranks.md.jinja2":     templatesRanksMdJinja2,
	"templates/stats.md.jinja2":     templatesStatsMdJinja2,
}

// AssetDebug is true if the assets were built with the debug flag enabled.
const AssetDebug = false

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//
//	data/
//	  foo.txt
//	  img/
//	    a.png
//	    b.png
//
// then AssetDir("data") would return []string{"foo.txt", "img"},
// AssetDir("data/img") would return []string{"a.png", "b.png"},
// AssetDir("foo.txt") and AssetDir("notexist") would return an error, and
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		canonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(canonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"templates": {nil, map[string]*bintree{
		"doc_index.md.gotmpl": {templatesDoc_indexMdGotmpl, map[string]*bintree{}},
		"doc_page.md.gotmpl":  {templatesDoc_pageMdGotmpl, map[string]*bintree{}},
		"header.md.gotmpl":    {templatesHeaderMdGotmpl, map[string]*bintree{}},
		"header.md.jinja2":    {templatesHeaderMdJinja2, map[string]*bintree{}},
		"ranks.md.gotmpl":     {templatesRanksMdGotmpl, map[string]*bintree{}},
		"ranks.md.jinja2":     {templatesRanksMdJinja2, map[string]*bintree{}},
		"stats.md.jinja2":     {templatesStatsMdJinja2, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory.
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = os.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	return os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
}

// RestoreAssets restores an asset under the given directory recursively.
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(canonicalName, "/")...)...)
}
